version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'type: dependencies'
      - github_actions

  - package-ecosystem: npm
    directory: /
    schedule:
      interval: monthly
    labels:
      - 'type: dependencies'
      - 'javascript'
