on:
  issue_comment:
    types:
      - created
jobs:
  container-tests:
    runs-on: ubuntu-22.04
    name: "GitHub summary test for testing farm as a github action"

    if: |
      github.event.issue.pull_request
      && contains(github.event.comment.body, '[test]')
      && contains(fromJson('["OWNER", "MEMBER"]'), github.event.comment.author_association)

    steps:
      - name: Checkout repo
        uses: actions/checkout@v4
        with:
          ref: "refs/pull/${{ github.event.issue.number }}/head"

      - name: Run the tests
        uses: ./
        with:
          api_key: ${{ secrets.TF_PUBLIC_API_KEY }}
          git_ref: "main"
          tmt_plan_regex: "smoke_plan"
          pull_request_status_name: "GitHub summary test"
          create_github_summary: "user_defined_key=user_defined_value"
          update_pull_request_status: "true"
