---

name: GitHub Tag Update

on:
  release:
    types: [ published, edited ]

permissions:
  contents: read

jobs:
  tag-update:
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
      - name: Repository checkout
        uses: actions/checkout@v3

      - name: Update tag
        uses: Actions-R-Us/actions-tagger@v2
        with:
          publish_latest_tag: false
          token: ${{ secrets.GITHUB_TOKEN }}
